export {default as Dashboard} from './Dashboard/Dashboard'
export {default as Login} from './Login/Login'
export {default as About} from './About/About'
export {default as Settings} from './Settings/Settings'
export {default as LandingScreen} from './LandingScreen/LandingScreen'
export {default as More} from './More/More'
